### ISSUE TITLE
About  RNA-FM_pretrained.pth

### ISSUE THREAD

**Issue by Dowson0** [ml4bio/RNA-FM#17]
Hello, thank you for developing RNA-FM. I want to use this software to generate RNA secondary structure. I have put RNA-FM_pretrained.pth into the pretrained folder. But when I start training, `python launch/predict.py --config="pretrained/ss_prediction.yml" \
--data_path="./data/examples/example.fasta" --save_dir="./resuts" \
--save_frequency 1it` appears to download the model.
Due to my slow network, the download takes 65 hours. How can I solve this problem?
![Uploading 屏幕截图 2024-11-19 170513.jpeg…]()

**Comment by Dowson0** [comment]
root@autodl-container-f7da119752-4edfb525:~/autodl-tmp/RNA-FM-main/redevelop# python launch/predict.py --config="prete.fasta" --save_dir="./resuts" --save_frequency 1
work_dir:/root/autodl-tmp/RNA-FM-main/redevelop/.
2024-11-19 19:21:00,714 prediction INFO: Using 1 GPUS, GPU ID: 0
2024-11-19 19:21:00,715 prediction INFO: Loaded configuration file pretrained/ss_prediction.yml
2024-11-19 19:21:00,715 prediction INFO: Model File:pretrained/Models/SS/RNA-FM-ResNet_PDB-All.pth
2024-11-19 19:21:00,715 prediction INFO: Batch Size:1
2024-11-19 19:21:00,715 prediction INFO: Threshold:0.33993712
2024-11-19 19:21:00,715 prediction INFO: Prediction Dataset: ./data/examples/example.fasta
Traceback (most recent call last):
  File "/root/autodl-tmp/RNA-FM-main/redevelop/launch/predict.py", line 236, in <module>
    main()
  File "/root/autodl-tmp/RNA-FM-main/redevelop/launch/predict.py", line 230, in main
    predict(cfg, args.save_embeddings, args.save_embeddings_format, args.save_frequency, args.save_file_prefix,
  File "/root/autodl-tmp/RNA-FM-main/redevelop/launch/predict.py", line 47, in predict
    model.load_param("overall", cfg.EVAL.WEIGHT_PATH)
  File "/root/autodl-tmp/RNA-FM-main/redevelop/./model/baseline.py", line 251, in load_param
    param_dict = torch.load(model_path, map_location="cpu")  #["model"]
  File "/root/miniconda3/envs/dgbert/lib/python3.9/site-packages/torch/serialization.py", line 699, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/root/miniconda3/envs/dgbert/lib/python3.9/site-packages/torch/serialization.py", line 230, in _open_file_lik
    return _open_file(name_or_buffer, mode)
  File "/root/miniconda3/envs/dgbert/lib/python3.9/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'pretrained/Models/SS/RNA-FM-ResNet_PDB-All.pth'
how can i get the RNA-FM-ResNet_PDB-All.pth
